/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Threading;
using System.Threading.Tasks;
using Tanks.ApiClient.Client;
using Tanks.ApiClient.Model;

namespace Tanks.ApiClient.Api
{

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMatchesApiSync : IApiAccessor
    {

        #region Synchronous Operations

        /// <summary>
        ///     Record match result
        /// </summary>
        /// <remarks>
        ///     Record the result of a match and update player statistics
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recordMatchRequest"> (optional)</param>
        /// <returns>MatchResponse</returns>
        MatchResponse MatchesPost(RecordMatchRequest recordMatchRequest = default);

        /// <summary>
        ///     Record match result
        /// </summary>
        /// <remarks>
        ///     Record the result of a match and update player statistics
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recordMatchRequest"> (optional)</param>
        /// <returns>ApiResponse of MatchResponse</returns>
        ApiResponse<MatchResponse> MatchesPostWithHttpInfo(RecordMatchRequest recordMatchRequest = default);

        #endregion Synchronous Operations

    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMatchesApiAsync : IApiAccessor
    {

        #region Asynchronous Operations

        /// <summary>
        ///     Record match result
        /// </summary>
        /// <remarks>
        ///     Record the result of a match and update player statistics
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recordMatchRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MatchResponse</returns>
        Task<MatchResponse> MatchesPostAsync(RecordMatchRequest recordMatchRequest = default, CancellationToken cancellationToken = default);

        /// <summary>
        ///     Record match result
        /// </summary>
        /// <remarks>
        ///     Record the result of a match and update player statistics
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recordMatchRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MatchResponse)</returns>
        Task<ApiResponse<MatchResponse>>
            MatchesPostWithHttpInfoAsync(RecordMatchRequest recordMatchRequest = default, CancellationToken cancellationToken = default);

        #endregion Asynchronous Operations

    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMatchesApi : IMatchesApiSync, IMatchesApiAsync
    {
    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class MatchesApi : IDisposable, IMatchesApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        ///     Initializes a new instance of the <see cref="MatchesApi" /> class.
        ///     **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        ///     It's better to reuse the
        ///     <see
        ///         href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">
        ///         HttpClient
        ///         and HttpClientHandler
        ///     </see>
        ///     .
        /// </summary>
        /// <returns></returns>
        public MatchesApi() : this((string)null)
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MatchesApi" /> class.
        ///     **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        ///     It's better to reuse the
        ///     <see
        ///         href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">
        ///         HttpClient
        ///         and HttpClientHandler
        ///     </see>
        ///     .
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MatchesApi(string basePath)
        {
            Configuration = Tanks.ApiClient.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                new Configuration { BasePath = basePath }
            );
            ApiClient = new Client.ApiClient(Configuration.BasePath);
            Client = ApiClient;
            AsynchronousClient = ApiClient;
            ExceptionFactory = Tanks.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MatchesApi" /> class using Configuration object.
        ///     **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        ///     It's better to reuse the
        ///     <see
        ///         href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">
        ///         HttpClient
        ///         and HttpClientHandler
        ///     </see>
        ///     .
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MatchesApi(Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            Configuration = Tanks.ApiClient.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                configuration
            );
            ApiClient = new Client.ApiClient(Configuration.BasePath);
            Client = ApiClient;
            AsynchronousClient = ApiClient;
            ExceptionFactory = Tanks.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MatchesApi" /> class
        ///     using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MatchesApi(ISynchronousClient client, IAsynchronousClient asyncClient, IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            Client = client;
            AsynchronousClient = asyncClient;
            Configuration = configuration;
            ExceptionFactory = Tanks.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Holds the ApiClient if created
        /// </summary>
        public Client.ApiClient ApiClient { get; set; }

        /// <summary>
        ///     The client for accessing this underlying API asynchronously.
        /// </summary>
        public IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        ///     The client for accessing this underlying API synchronously.
        /// </summary>
        public ISynchronousClient Client { get; set; }

        /// <summary>
        ///     Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            ApiClient?.Dispose();
        }

        /// <summary>
        ///     Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return Configuration.BasePath;
        }

        /// <summary>
        ///     Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IReadableConfiguration Configuration { get; set; }

        /// <summary>
        ///     Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set => _exceptionFactory = value;
        }

        /// <summary>
        ///     Record match result Record the result of a match and update player statistics
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recordMatchRequest"> (optional)</param>
        /// <returns>MatchResponse</returns>
        public MatchResponse MatchesPost(RecordMatchRequest recordMatchRequest = default)
        {
            var localVarResponse = MatchesPostWithHttpInfo(recordMatchRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///     Record match result Record the result of a match and update player statistics
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recordMatchRequest"> (optional)</param>
        /// <returns>ApiResponse of MatchResponse</returns>
        public ApiResponse<MatchResponse> MatchesPostWithHttpInfo(RecordMatchRequest recordMatchRequest = default)
        {
            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new[]
            {
                "application/json"
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = recordMatchRequest;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = Client.Post<MatchResponse>("/matches", localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("MatchesPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///     Record match result Record the result of a match and update player statistics
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recordMatchRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MatchResponse</returns>
        public async Task<MatchResponse> MatchesPostAsync(RecordMatchRequest recordMatchRequest = default, CancellationToken cancellationToken = default)
        {
            var task = MatchesPostWithHttpInfoAsync(recordMatchRequest, cancellationToken);
            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            Tanks.ApiClient.Client.ApiResponse<MatchResponse> localVarResponse = await task;
            #endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///     Record match result Record the result of a match and update player statistics
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recordMatchRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MatchResponse)</returns>
        public async Task<ApiResponse<MatchResponse>> MatchesPostWithHttpInfoAsync(RecordMatchRequest recordMatchRequest = default,
            CancellationToken cancellationToken = default)
        {

            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new[]
            {
                "application/json"
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };


            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = recordMatchRequest;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + Configuration.AccessToken);
            }

            // make the HTTP request

            var task = AsynchronousClient.PostAsync<MatchResponse>("/matches", localVarRequestOptions, Configuration, cancellationToken);

            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            var localVarResponse = await task;
            #endif

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("MatchesPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }
    }
}
