/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Threading;
using System.Threading.Tasks;
using Tanks.ApiClient.Client;
using Tanks.ApiClient.Model;

namespace Tanks.ApiClient.Api
{

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApiSync : IApiAccessor
    {

        #region Synchronous Operations

        /// <summary>
        ///     Get user information
        /// </summary>
        /// <remarks>
        ///     Retrieve user information by user ID
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>UserResponse</returns>
        UserResponse UsersIdGet(string id);

        /// <summary>
        ///     Get user information
        /// </summary>
        /// <remarks>
        ///     Retrieve user information by user ID
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of UserResponse</returns>
        ApiResponse<UserResponse> UsersIdGetWithHttpInfo(string id);

        /// <summary>
        ///     Update user name
        /// </summary>
        /// <remarks>
        ///     Update the name of a user
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateNameRequest"> (optional)</param>
        /// <returns>UserResponse</returns>
        UserResponse UsersIdNamePatch(string id, UpdateNameRequest updateNameRequest = default);

        /// <summary>
        ///     Update user name
        /// </summary>
        /// <remarks>
        ///     Update the name of a user
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateNameRequest"> (optional)</param>
        /// <returns>ApiResponse of UserResponse</returns>
        ApiResponse<UserResponse> UsersIdNamePatchWithHttpInfo(string id, UpdateNameRequest updateNameRequest = default);

        /// <summary>
        ///     User login
        /// </summary>
        /// <remarks>
        ///     Authenticate user with userId and refresh token
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginRequest"> (optional)</param>
        /// <returns>AuthResponse</returns>
        AuthResponse UsersLoginPost(LoginRequest loginRequest = default);

        /// <summary>
        ///     User login
        /// </summary>
        /// <remarks>
        ///     Authenticate user with userId and refresh token
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginRequest"> (optional)</param>
        /// <returns>ApiResponse of AuthResponse</returns>
        ApiResponse<AuthResponse> UsersLoginPostWithHttpInfo(LoginRequest loginRequest = default);

        /// <summary>
        ///     Create new user
        /// </summary>
        /// <remarks>
        ///     Creates a new user and returns authentication tokens
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <returns>AuthResponse</returns>
        AuthResponse UsersPost(CreateUserRequest createUserRequest = default);

        /// <summary>
        ///     Create new user
        /// </summary>
        /// <remarks>
        ///     Creates a new user and returns authentication tokens
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <returns>ApiResponse of AuthResponse</returns>
        ApiResponse<AuthResponse> UsersPostWithHttpInfo(CreateUserRequest createUserRequest = default);

        #endregion Synchronous Operations

    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApiAsync : IApiAccessor
    {

        #region Asynchronous Operations

        /// <summary>
        ///     Get user information
        /// </summary>
        /// <remarks>
        ///     Retrieve user information by user ID
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserResponse</returns>
        Task<UserResponse> UsersIdGetAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>
        ///     Get user information
        /// </summary>
        /// <remarks>
        ///     Retrieve user information by user ID
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserResponse)</returns>
        Task<ApiResponse<UserResponse>> UsersIdGetWithHttpInfoAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>
        ///     Update user name
        /// </summary>
        /// <remarks>
        ///     Update the name of a user
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateNameRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserResponse</returns>
        Task<UserResponse> UsersIdNamePatchAsync(string id, UpdateNameRequest updateNameRequest = default, CancellationToken cancellationToken = default);

        /// <summary>
        ///     Update user name
        /// </summary>
        /// <remarks>
        ///     Update the name of a user
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateNameRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserResponse)</returns>
        Task<ApiResponse<UserResponse>> UsersIdNamePatchWithHttpInfoAsync(string id, UpdateNameRequest updateNameRequest = default,
            CancellationToken cancellationToken = default);

        /// <summary>
        ///     User login
        /// </summary>
        /// <remarks>
        ///     Authenticate user with userId and refresh token
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthResponse</returns>
        Task<AuthResponse> UsersLoginPostAsync(LoginRequest loginRequest = default, CancellationToken cancellationToken = default);

        /// <summary>
        ///     User login
        /// </summary>
        /// <remarks>
        ///     Authenticate user with userId and refresh token
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthResponse)</returns>
        Task<ApiResponse<AuthResponse>> UsersLoginPostWithHttpInfoAsync(LoginRequest loginRequest = default, CancellationToken cancellationToken = default);

        /// <summary>
        ///     Create new user
        /// </summary>
        /// <remarks>
        ///     Creates a new user and returns authentication tokens
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthResponse</returns>
        Task<AuthResponse> UsersPostAsync(CreateUserRequest createUserRequest = default, CancellationToken cancellationToken = default);

        /// <summary>
        ///     Create new user
        /// </summary>
        /// <remarks>
        ///     Creates a new user and returns authentication tokens
        /// </remarks>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthResponse)</returns>
        Task<ApiResponse<AuthResponse>> UsersPostWithHttpInfoAsync(CreateUserRequest createUserRequest = default, CancellationToken cancellationToken = default);

        #endregion Asynchronous Operations

    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApi : IUsersApiSync, IUsersApiAsync
    {
    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class UsersApi : IDisposable, IUsersApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        ///     Initializes a new instance of the <see cref="UsersApi" /> class.
        ///     **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        ///     It's better to reuse the
        ///     <see
        ///         href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">
        ///         HttpClient
        ///         and HttpClientHandler
        ///     </see>
        ///     .
        /// </summary>
        /// <returns></returns>
        public UsersApi() : this((string)null)
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="UsersApi" /> class.
        ///     **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        ///     It's better to reuse the
        ///     <see
        ///         href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">
        ///         HttpClient
        ///         and HttpClientHandler
        ///     </see>
        ///     .
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public UsersApi(string basePath)
        {
            Configuration = Tanks.ApiClient.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                new Configuration { BasePath = basePath }
            );
            ApiClient = new Client.ApiClient(Configuration.BasePath);
            Client = ApiClient;
            AsynchronousClient = ApiClient;
            ExceptionFactory = Tanks.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="UsersApi" /> class using Configuration object.
        ///     **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        ///     It's better to reuse the
        ///     <see
        ///         href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">
        ///         HttpClient
        ///         and HttpClientHandler
        ///     </see>
        ///     .
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public UsersApi(Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            Configuration = Tanks.ApiClient.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                configuration
            );
            ApiClient = new Client.ApiClient(Configuration.BasePath);
            Client = ApiClient;
            AsynchronousClient = ApiClient;
            ExceptionFactory = Tanks.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="UsersApi" /> class
        ///     using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public UsersApi(ISynchronousClient client, IAsynchronousClient asyncClient, IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            Client = client;
            AsynchronousClient = asyncClient;
            Configuration = configuration;
            ExceptionFactory = Tanks.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Holds the ApiClient if created
        /// </summary>
        public Client.ApiClient ApiClient { get; set; }

        /// <summary>
        ///     The client for accessing this underlying API asynchronously.
        /// </summary>
        public IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        ///     The client for accessing this underlying API synchronously.
        /// </summary>
        public ISynchronousClient Client { get; set; }

        /// <summary>
        ///     Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            ApiClient?.Dispose();
        }

        /// <summary>
        ///     Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return Configuration.BasePath;
        }

        /// <summary>
        ///     Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IReadableConfiguration Configuration { get; set; }

        /// <summary>
        ///     Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set => _exceptionFactory = value;
        }

        /// <summary>
        ///     Get user information Retrieve user information by user ID
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>UserResponse</returns>
        public UserResponse UsersIdGet(string id)
        {
            var localVarResponse = UsersIdGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///     Get user information Retrieve user information by user ID
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of UserResponse</returns>
        public ApiResponse<UserResponse> UsersIdGetWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UsersApi->UsersIdGet");

            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new string[]
            {
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", ClientUtils.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = Client.Get<UserResponse>("/users/{id}", localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("UsersIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///     Get user information Retrieve user information by user ID
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserResponse</returns>
        public async Task<UserResponse> UsersIdGetAsync(string id, CancellationToken cancellationToken = default)
        {
            var task = UsersIdGetWithHttpInfoAsync(id, cancellationToken);
            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            Tanks.ApiClient.Client.ApiResponse<UserResponse> localVarResponse = await task;
            #endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///     Get user information Retrieve user information by user ID
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserResponse)</returns>
        public async Task<ApiResponse<UserResponse>> UsersIdGetWithHttpInfoAsync(string id, CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UsersApi->UsersIdGet");


            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new string[]
            {
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };


            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", ClientUtils.ParameterToString(id)); // path parameter

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + Configuration.AccessToken);
            }

            // make the HTTP request

            var task = AsynchronousClient.GetAsync<UserResponse>("/users/{id}", localVarRequestOptions, Configuration, cancellationToken);

            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            var localVarResponse = await task;
            #endif

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("UsersIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///     Update user name Update the name of a user
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateNameRequest"> (optional)</param>
        /// <returns>UserResponse</returns>
        public UserResponse UsersIdNamePatch(string id, UpdateNameRequest updateNameRequest = default)
        {
            var localVarResponse = UsersIdNamePatchWithHttpInfo(id, updateNameRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///     Update user name Update the name of a user
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateNameRequest"> (optional)</param>
        /// <returns>ApiResponse of UserResponse</returns>
        public ApiResponse<UserResponse> UsersIdNamePatchWithHttpInfo(string id, UpdateNameRequest updateNameRequest = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UsersApi->UsersIdNamePatch");

            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new[]
            {
                "application/json"
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = updateNameRequest;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = Client.Patch<UserResponse>("/users/{id}/name", localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("UsersIdNamePatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///     Update user name Update the name of a user
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateNameRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserResponse</returns>
        public async Task<UserResponse> UsersIdNamePatchAsync(string id, UpdateNameRequest updateNameRequest = default,
            CancellationToken cancellationToken = default)
        {
            var task = UsersIdNamePatchWithHttpInfoAsync(id, updateNameRequest, cancellationToken);
            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            Tanks.ApiClient.Client.ApiResponse<UserResponse> localVarResponse = await task;
            #endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///     Update user name Update the name of a user
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateNameRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserResponse)</returns>
        public async Task<ApiResponse<UserResponse>> UsersIdNamePatchWithHttpInfoAsync(string id, UpdateNameRequest updateNameRequest = default,
            CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UsersApi->UsersIdNamePatch");


            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new[]
            {
                "application/json"
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };


            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = updateNameRequest;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + Configuration.AccessToken);
            }

            // make the HTTP request

            var task = AsynchronousClient.PatchAsync<UserResponse>("/users/{id}/name", localVarRequestOptions, Configuration, cancellationToken);

            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            var localVarResponse = await task;
            #endif

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("UsersIdNamePatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///     User login Authenticate user with userId and refresh token
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginRequest"> (optional)</param>
        /// <returns>AuthResponse</returns>
        public AuthResponse UsersLoginPost(LoginRequest loginRequest = default)
        {
            var localVarResponse = UsersLoginPostWithHttpInfo(loginRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///     User login Authenticate user with userId and refresh token
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginRequest"> (optional)</param>
        /// <returns>ApiResponse of AuthResponse</returns>
        public ApiResponse<AuthResponse> UsersLoginPostWithHttpInfo(LoginRequest loginRequest = default)
        {
            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new[]
            {
                "application/json"
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = loginRequest;


            // make the HTTP request
            var localVarResponse = Client.Post<AuthResponse>("/users/login", localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("UsersLoginPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///     User login Authenticate user with userId and refresh token
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthResponse</returns>
        public async Task<AuthResponse> UsersLoginPostAsync(LoginRequest loginRequest = default, CancellationToken cancellationToken = default)
        {
            var task = UsersLoginPostWithHttpInfoAsync(loginRequest, cancellationToken);
            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            Tanks.ApiClient.Client.ApiResponse<AuthResponse> localVarResponse = await task;
            #endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///     User login Authenticate user with userId and refresh token
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthResponse)</returns>
        public async Task<ApiResponse<AuthResponse>> UsersLoginPostWithHttpInfoAsync(LoginRequest loginRequest = default,
            CancellationToken cancellationToken = default)
        {

            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new[]
            {
                "application/json"
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };


            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = loginRequest;


            // make the HTTP request

            var task = AsynchronousClient.PostAsync<AuthResponse>("/users/login", localVarRequestOptions, Configuration, cancellationToken);

            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            var localVarResponse = await task;
            #endif

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("UsersLoginPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///     Create new user Creates a new user and returns authentication tokens
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <returns>AuthResponse</returns>
        public AuthResponse UsersPost(CreateUserRequest createUserRequest = default)
        {
            var localVarResponse = UsersPostWithHttpInfo(createUserRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///     Create new user Creates a new user and returns authentication tokens
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <returns>ApiResponse of AuthResponse</returns>
        public ApiResponse<AuthResponse> UsersPostWithHttpInfo(CreateUserRequest createUserRequest = default)
        {
            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new[]
            {
                "application/json"
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createUserRequest;


            // make the HTTP request
            var localVarResponse = Client.Post<AuthResponse>("/users", localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("UsersPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///     Create new user Creates a new user and returns authentication tokens
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuthResponse</returns>
        public async Task<AuthResponse> UsersPostAsync(CreateUserRequest createUserRequest = default, CancellationToken cancellationToken = default)
        {
            var task = UsersPostWithHttpInfoAsync(createUserRequest, cancellationToken);
            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            Tanks.ApiClient.Client.ApiResponse<AuthResponse> localVarResponse = await task;
            #endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///     Create new user Creates a new user and returns authentication tokens
        /// </summary>
        /// <exception cref="Tanks.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuthResponse)</returns>
        public async Task<ApiResponse<AuthResponse>> UsersPostWithHttpInfoAsync(CreateUserRequest createUserRequest = default,
            CancellationToken cancellationToken = default)
        {

            var localVarRequestOptions = new RequestOptions();

            var _contentTypes = new[]
            {
                "application/json"
            };

            // to determine the Accept header
            var _accepts = new[]
            {
                "application/json"
            };


            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createUserRequest;


            // make the HTTP request

            var task = AsynchronousClient.PostAsync<AuthResponse>("/users", localVarRequestOptions, Configuration, cancellationToken);

            #if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
            #else
            var localVarResponse = await task;
            #endif

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("UsersPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }
    }
}
