/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using UnityEngine.Networking;

namespace Tanks.ApiClient.Client
{
    /// <summary>
    /// Provides an awaiter for UnityWebRequestAsyncOperation to allow `await request.SendWebRequest()`
    /// in Unity async methods. Unity's AsyncOperation types are not awaitable by default, so this
    /// extension bridges that gap by converting the operation into a Task.
    /// </summary>
    public static class UnityWebRequestAwaiterExtensions
    {
        public static TaskAwaiter<UnityWebRequestAsyncOperation> GetAwaiter(this UnityWebRequestAsyncOperation asyncOp)
        {
            var tcs = new TaskCompletionSource<UnityWebRequestAsyncOperation>();
            asyncOp.completed += _ => tcs.SetResult(asyncOp);
            return tcs.Task.GetAwaiter();
        }
    }
}
