/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Tanks.ApiClient.Model
{
    /// <summary>
    ///     MatchResponseUpdatedStats
    /// </summary>
    [DataContract(Name = "MatchResponse_updatedStats")]
    public class MatchResponseUpdatedStats
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MatchResponseUpdatedStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchResponseUpdatedStats()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MatchResponseUpdatedStats" /> class.
        /// </summary>
        /// <param name="wins">wins (required).</param>
        /// <param name="losses">losses (required).</param>
        /// <param name="totalMatches">totalMatches (required).</param>
        public MatchResponseUpdatedStats(decimal wins = default, decimal losses = default, decimal totalMatches = default)
        {
            Wins = wins;
            Losses = losses;
            TotalMatches = totalMatches;
        }

        /// <summary>
        ///     Gets or Sets Wins
        /// </summary>
        [DataMember(Name = "wins", IsRequired = true, EmitDefaultValue = true)]
        public decimal Wins { get; set; }

        /// <summary>
        ///     Gets or Sets Losses
        /// </summary>
        [DataMember(Name = "losses", IsRequired = true, EmitDefaultValue = true)]
        public decimal Losses { get; set; }

        /// <summary>
        ///     Gets or Sets TotalMatches
        /// </summary>
        [DataMember(Name = "totalMatches", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalMatches { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MatchResponseUpdatedStats {\n");
            sb.Append("  Wins: ").Append(Wins).Append("\n");
            sb.Append("  Losses: ").Append(Losses).Append("\n");
            sb.Append("  TotalMatches: ").Append(TotalMatches).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
