/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Tanks.ApiClient.Client.OpenAPIDateConverter;

namespace Tanks.ApiClient.Model
{
    /// <summary>
    /// MatchResponseMatch
    /// </summary>
    [DataContract(Name = "MatchResponse_match")]
    public partial class MatchResponseMatch
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchResponseMatch" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchResponseMatch() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchResponseMatch" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="winnerId">winnerId (required).</param>
        /// <param name="loserId">loserId (required).</param>
        /// <param name="playedAt">playedAt (required).</param>
        public MatchResponseMatch(decimal id = default, decimal winnerId = default, decimal loserId = default, string playedAt = default)
        {
            this.Id = id;
            this.WinnerId = winnerId;
            this.LoserId = loserId;
            // to ensure "playedAt" is required (not null)
            if (playedAt == null)
            {
                throw new ArgumentNullException("playedAt is a required property for MatchResponseMatch and cannot be null");
            }
            this.PlayedAt = playedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Gets or Sets WinnerId
        /// </summary>
        [DataMember(Name = "winnerId", IsRequired = true, EmitDefaultValue = true)]
        public decimal WinnerId { get; set; }

        /// <summary>
        /// Gets or Sets LoserId
        /// </summary>
        [DataMember(Name = "loserId", IsRequired = true, EmitDefaultValue = true)]
        public decimal LoserId { get; set; }

        /// <summary>
        /// Gets or Sets PlayedAt
        /// </summary>
        [DataMember(Name = "playedAt", IsRequired = true, EmitDefaultValue = true)]
        public string PlayedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MatchResponseMatch {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  WinnerId: ").Append(WinnerId).Append("\n");
            sb.Append("  LoserId: ").Append(LoserId).Append("\n");
            sb.Append("  PlayedAt: ").Append(PlayedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
