/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Tanks.ApiClient.Model
{
    /// <summary>
    ///     MatchResponse
    /// </summary>
    [DataContract(Name = "MatchResponse")]
    public class MatchResponse
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MatchResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchResponse()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MatchResponse" /> class.
        /// </summary>
        /// <param name="match">match (required).</param>
        /// <param name="updatedStats">updatedStats (required).</param>
        public MatchResponse(MatchResponseMatch match = default, MatchResponseUpdatedStats updatedStats = default)
        {
            // to ensure "match" is required (not null)
            if (match == null)
            {
                throw new ArgumentNullException("match is a required property for MatchResponse and cannot be null");
            }
            Match = match;
            // to ensure "updatedStats" is required (not null)
            if (updatedStats == null)
            {
                throw new ArgumentNullException("updatedStats is a required property for MatchResponse and cannot be null");
            }
            UpdatedStats = updatedStats;
        }

        /// <summary>
        ///     Gets or Sets Match
        /// </summary>
        [DataMember(Name = "match", IsRequired = true, EmitDefaultValue = true)]
        public MatchResponseMatch Match { get; set; }

        /// <summary>
        ///     Gets or Sets UpdatedStats
        /// </summary>
        [DataMember(Name = "updatedStats", IsRequired = true, EmitDefaultValue = true)]
        public MatchResponseUpdatedStats UpdatedStats { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MatchResponse {\n");
            sb.Append("  Match: ").Append(Match).Append("\n");
            sb.Append("  UpdatedStats: ").Append(UpdatedStats).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
