/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Tanks.ApiClient.Model
{
    /// <summary>
    ///     RankingResponse
    /// </summary>
    [DataContract(Name = "RankingResponse")]
    public class RankingResponse
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RankingResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RankingResponse()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="RankingResponse" /> class.
        /// </summary>
        /// <param name="rankings">rankings (required).</param>
        /// <param name="currentUser">currentUser (required).</param>
        public RankingResponse(List<RankingResponseRankingsInner> rankings = default, RankingResponseRankingsInner currentUser = default)
        {
            // to ensure "rankings" is required (not null)
            if (rankings == null)
            {
                throw new ArgumentNullException("rankings is a required property for RankingResponse and cannot be null");
            }
            Rankings = rankings;
            // to ensure "currentUser" is required (not null)
            if (currentUser == null)
            {
                throw new ArgumentNullException("currentUser is a required property for RankingResponse and cannot be null");
            }
            CurrentUser = currentUser;
        }

        /// <summary>
        ///     Gets or Sets Rankings
        /// </summary>
        [DataMember(Name = "rankings", IsRequired = true, EmitDefaultValue = true)]
        public List<RankingResponseRankingsInner> Rankings { get; set; }

        /// <summary>
        ///     Gets or Sets CurrentUser
        /// </summary>
        [DataMember(Name = "currentUser", IsRequired = true, EmitDefaultValue = true)]
        public RankingResponseRankingsInner CurrentUser { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RankingResponse {\n");
            sb.Append("  Rankings: ").Append(Rankings).Append("\n");
            sb.Append("  CurrentUser: ").Append(CurrentUser).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
