/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Tanks.ApiClient.Model
{
    /// <summary>
    ///     RankingResponseRankingsInner
    /// </summary>
    [DataContract(Name = "RankingResponse_rankings_inner")]
    public class RankingResponseRankingsInner
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RankingResponseRankingsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RankingResponseRankingsInner()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="RankingResponseRankingsInner" /> class.
        /// </summary>
        /// <param name="rank">rank (required).</param>
        /// <param name="userId">userId (required).</param>
        /// <param name="userName">userName (required).</param>
        /// <param name="winRate">winRate (required).</param>
        /// <param name="wins">wins (required).</param>
        /// <param name="losses">losses (required).</param>
        /// <param name="totalMatches">totalMatches (required).</param>
        public RankingResponseRankingsInner(decimal? rank = default, decimal userId = default, string userName = default, decimal winRate = default,
            decimal wins = default, decimal losses = default, decimal totalMatches = default)
        {
            // to ensure "rank" is required (not null)
            if (rank == null)
            {
                throw new ArgumentNullException("rank is a required property for RankingResponseRankingsInner and cannot be null");
            }
            Rank = rank;
            UserId = userId;
            // to ensure "userName" is required (not null)
            if (userName == null)
            {
                throw new ArgumentNullException("userName is a required property for RankingResponseRankingsInner and cannot be null");
            }
            UserName = userName;
            WinRate = winRate;
            Wins = wins;
            Losses = losses;
            TotalMatches = totalMatches;
        }

        /// <summary>
        ///     Gets or Sets Rank
        /// </summary>
        [DataMember(Name = "rank", IsRequired = true, EmitDefaultValue = true)]
        public decimal? Rank { get; set; }

        /// <summary>
        ///     Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public decimal UserId { get; set; }

        /// <summary>
        ///     Gets or Sets UserName
        /// </summary>
        [DataMember(Name = "userName", IsRequired = true, EmitDefaultValue = true)]
        public string UserName { get; set; }

        /// <summary>
        ///     Gets or Sets WinRate
        /// </summary>
        [DataMember(Name = "winRate", IsRequired = true, EmitDefaultValue = true)]
        public decimal WinRate { get; set; }

        /// <summary>
        ///     Gets or Sets Wins
        /// </summary>
        [DataMember(Name = "wins", IsRequired = true, EmitDefaultValue = true)]
        public decimal Wins { get; set; }

        /// <summary>
        ///     Gets or Sets Losses
        /// </summary>
        [DataMember(Name = "losses", IsRequired = true, EmitDefaultValue = true)]
        public decimal Losses { get; set; }

        /// <summary>
        ///     Gets or Sets TotalMatches
        /// </summary>
        [DataMember(Name = "totalMatches", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalMatches { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RankingResponseRankingsInner {\n");
            sb.Append("  Rank: ").Append(Rank).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  WinRate: ").Append(WinRate).Append("\n");
            sb.Append("  Wins: ").Append(Wins).Append("\n");
            sb.Append("  Losses: ").Append(Losses).Append("\n");
            sb.Append("  TotalMatches: ").Append(TotalMatches).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
