/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Tanks.ApiClient.Model
{
    /// <summary>
    ///     RecordMatchRequest
    /// </summary>
    [DataContract(Name = "RecordMatchRequest")]
    public class RecordMatchRequest
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RecordMatchRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecordMatchRequest()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="RecordMatchRequest" /> class.
        /// </summary>
        /// <param name="visitorId">visitorId (required).</param>
        /// <param name="visitorScore">visitorScore (required).</param>
        /// <param name="homeScore">homeScore (required).</param>
        public RecordMatchRequest(int visitorId = default, int visitorScore = default, int homeScore = default)
        {
            VisitorId = visitorId;
            VisitorScore = visitorScore;
            HomeScore = homeScore;
        }

        /// <summary>
        ///     Gets or Sets VisitorId
        /// </summary>
        [DataMember(Name = "visitorId", IsRequired = true, EmitDefaultValue = true)]
        public int VisitorId { get; set; }

        /// <summary>
        ///     Gets or Sets VisitorScore
        /// </summary>
        [DataMember(Name = "visitorScore", IsRequired = true, EmitDefaultValue = true)]
        public int VisitorScore { get; set; }

        /// <summary>
        ///     Gets or Sets HomeScore
        /// </summary>
        [DataMember(Name = "homeScore", IsRequired = true, EmitDefaultValue = true)]
        public int HomeScore { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecordMatchRequest {\n");
            sb.Append("  VisitorId: ").Append(VisitorId).Append("\n");
            sb.Append("  VisitorScore: ").Append(VisitorScore).Append("\n");
            sb.Append("  HomeScore: ").Append(HomeScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
