/*
 * Game API
 *
 * Unity game backend API for user management, authentication, matches, and rankings
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Tanks.ApiClient.Model
{
    /// <summary>
    ///     RefreshTokenRequest
    /// </summary>
    [DataContract(Name = "RefreshTokenRequest")]
    public class RefreshTokenRequest
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RefreshTokenRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RefreshTokenRequest()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="RefreshTokenRequest" /> class.
        /// </summary>
        /// <param name="refreshToken">refreshToken (required).</param>
        public RefreshTokenRequest(Guid refreshToken = default)
        {
            RefreshToken = refreshToken;
        }

        /// <summary>
        ///     Gets or Sets RefreshToken
        /// </summary>
        [DataMember(Name = "refreshToken", IsRequired = true, EmitDefaultValue = true)]
        public Guid RefreshToken { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RefreshTokenRequest {\n");
            sb.Append("  RefreshToken: ").Append(RefreshToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
