name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  inspect-code:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-6000.2.7f2-linux-il2cpp-3
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      # see https://github.com/game-ci/unity-builder/issues/497#issuecomment-1407712495
      - name: Generate .sln via Unity
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        run: |
          unity-editor -nographics -logFile /dev/stdout -quit -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD" -serial "$UNITY_SERIAL"
          unity-editor -nographics -logFile /dev/stdout -projectPath ./tanks -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution -quit

      # TODO: remove this after verifying .sln generation
      - name: print .sln files
        continue-on-error: true
        run: ls -R tanks/*.sln

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: false

      - name: Annotate
        uses: JetBrains/ReSharper-InspectCode@v0.11
        with:
          solution: ./tanks/tanks.sln
          eXtensions: JetBrains.Unity
          tool-version: 2025.2.3
          output: results.sarif.json
          sEverity: WARNING

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif.json

    permissions:
      contents: read
      security-events: write
