name: Delete Merge Branch Cache on PR Close
on:
  pull_request:
    types:
      - closed
jobs:
  cleanup:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          REPO=${{ github.repository }}
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
          set +e
          for cacheKey in $cacheKeysForPR
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

